{
 "title": "CTM 设备健康",
 "tags": [
  "ctm",
  "devices",
  "zabbix"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "zbx_group", "label": "Zabbix 组", "query": "*" },
   {
    "name": "zbx_host",
    "label": "Zabbix 主机",
    "query": "417交换机,PDU_UPS_1,PDU_UPS_3,PDU_市电,Server01,Server03,Server04,Server05,Server06,Server07,Server08,Server09,Server10,UPS,南昌云服务器,广州云服务器,核心交换机,福州云服务器"
   }
  ]
 },
 "panels": [
  {
   "title": "Agent Ping",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "/Zabbix agent ping|Zabbix agent availability|SNMP agent availability|ICMP ping|zabbix\\[host,(agent|snmp),available\\]|icmpping/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "ICMP Ping",
   "type": "stat",
   "gridPos": { "x": 4, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "ICMP ping" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU 负载",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "$zbx_group" },
     "host": { "filter": "$zbx_host" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "内存占用",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$zbx_group" },
     "host": { "filter": "$zbx_host" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU1 温度",
   "type": "stat",
   "gridPos": { "x": 4, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "/CPU1 Temp Value|CPU1 Temperature, C|CPU package temperature|sensor\\.temp\\.value\\[coretemp\\.package_0\\]|cpu\\.temp1/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "CPU2 温度",
   "type": "stat",
   "gridPos": { "x": 8, "y": 4, "w": 4, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "/CPU2 Temp Value|CPU2 Temperature, C|CPU core [0-9]+ temperature|sensor\\.temp\\.value\\[coretemp\\.core_[0-9]+\\]|cpu\\.temp2/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "设备当前问题",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 12 },
   "targets": [
    {
     "application": { "filter": "" },
     "countTriggersBy": "problems",
     "evaltype": "0",
     "group": { "filter": "$zbx_group" },
     "host": { "filter": "$zbx_host" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "mode": 5,
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "severity",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": false,
      "minSeverity": 0
     }
    }
   ]
  },
  {
   "title": "主机 CPU / 内存趋势",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "$zbx_group" },
     "host": { "filter": "$zbx_host" },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$zbx_group" },
     "host": { "filter": "$zbx_host" },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "硬件温度趋势",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "/CPU1 Temp Value|CPU1 Temperature, C|CPU package temperature|sensor\\.temp\\.value\\[coretemp\\.package_0\\]|cpu\\.temp1/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "/CPU2 Temp Value|CPU2 Temperature, C|CPU core [0-9]+ temperature|sensor\\.temp\\.value\\[coretemp\\.core_[0-9]+\\]|cpu\\.temp2/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "硬件、SNMP、IPMI 当前值",
   "type": "table",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$zbx_group" },
     "host": { "filter": "$zbx_host" },
     "item": {
      "filter": "/[Tt]emperature|Fan|Power|Voltage|UPS|Status|Serial|sensor|ipmi|IPMI|Temp/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "系统与资产文本项",
   "type": "table",
   "gridPos": { "x": 0, "y": 29, "w": 24, "h": 8 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$zbx_group" },
     "host": { "filter": "$zbx_host" },
     "item": {
      "filter": "/Host name of Zabbix agent running|Operating system|Operating system architecture|System description|System name|Version of Zabbix agent running|Hardware model name|Hardware serial number|Firmware version|System contact details|System location|System object ID|Model name|Serial number/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "mode": 2,
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "slaInterval": "none"
    }
   ]
  }
 ]
}