{
 "title": "CTM 机器详情",
 "tags": [
  "ctm",
  "zabbix",
  "server-trends"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "machine",
    "label": "机器",
    "query": "Server01,Server03,Server04,Server05,Server06,Server07,Server08,Server09,Server10,南昌云服务器,广州云服务器,福州云服务器"
   }
  ]
 },
 "panels": [
  {
   "title": "系统资源趋势",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/^(System|Hardware)$/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": { "filter": "CPU utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/^(System|Hardware)$/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": { "filter": "Memory utilization" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "网卡速率趋势",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/^(System|Hardware)$/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": { "filter": "/Bits received|Bits sent/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "硬盘使用率趋势",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/^(System|Hardware)$/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": { "filter": "/FS .*Space: Used, in %/" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "健康探测趋势",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": {
      "filter": "/Zabbix agent ping|Zabbix agent availability|SNMP agent availability|ICMP ping|zabbix\\[host,(agent|snmp),available\\]|icmpping/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "硬件温度趋势",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": {
      "filter": "/Temp Value|[Tt]emperature(?:, C)?|sensor\\.temp\\.value|cpu\\.temp|ipmi\\.value.*[Tt]emperature/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "风扇转速趋势",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 32, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "rpm" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": {
      "filter": "/Fan.*[Ss]peed|FAN.*speed|sensor\\.fan\\.speed/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "硬件传感器当前值",
   "type": "table",
   "gridPos": { "x": 12, "y": 32, "w": 12, "h": 8 },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "evaltype": "0",
     "group": { "filter": "/.*/" },
     "host": {
      "filter": "/(^$machine$|^sys_$machine$|^phy_$machine$)/"
     },
     "item": {
      "filter": "/Current state|Uptime|Fan.*[Ss]peed|FAN.*speed|sensor\\.fan\\.speed|Temp Value|[Tt]emperature(?:, C)?|sensor\\.temp\\.value|cpu\\.temp|ipmi\\.value.*[Tt]emperature|watts|Power/"
     },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "minSeverity": 3,
     "options": {
      "count": false,
      "disableDataAlignment": true,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}